# Navigation Links
#   The weight parameter defines the order that the links will appear in.
main:
  - name: Home
    url: /
    weight: 10
    params:
      align: left  # 左侧对齐

  - name: Topics
    url: tags/
    weight: 20
    params:
      align: left  # 左侧对齐

  - name: About
    url: about/
    weight: 30
    params:
      align: right  # 左侧对齐